### ISSUE TITLE
Optimize Compiled binary size

### ISSUE THREAD

**Issue by thangpqgm** [Shopify/shopify-function-rust#102]
Shopify sets a limit for Compiled binary size of 256 kb, and I'm having trouble because I haven't put a single line of code in and the Compiled binary size is already 155kb.
Below is the content of my run.graphql file.

```
query Input {
  cart {
    lines {
      id
      attribute(key: "_my_key") {
        key
        value
      }
      cost {
        amountPerQuantity {
          amount
        }
      }
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
    }
  }
  discountNode {
    metafield(namespace: "$app:function", key: "function-configuration") {
      value
    }
  }
}

```

I have done measurements and found that with just 3 lines 
```
 cost {
        amountPerQuantity {
          amount
        }
      }
```
 it has increased 40kb, 

Please provide a solution or guide me to solve this, I have a list of functions that need to be implemented and "40kb" took up 50% of what I wrote.
Thank you !

**Comment by nickwesselman** [comment]
Hi @thangpqgm  --

We have tips on reducing Rust binary size [here](https://shopify.dev/docs/apps/build/functions/programming-languages/rust-for-functions#binary-size-tips).
