### ISSUE TITLE
generate_types does not generate type customer inside buyer_identity

### ISSUE THREAD

**Issue by Rronz** [Shopify/shopify-function-rust#19]
Hi I'm new to rust so I might be wrong on this but while using this it seemed like generate_types is not generating a type for input.cart.buyer_identity.customer.

This is my input 

query Input {
  cart {
    buyerIdentity {
      customer {
        hasAnyTag(tags: ["Credits"])
      }
    }
    cost {
      totalAmount {
        amount
      }
    }
  }
  paymentMethods {
    id
    name
  }
  paymentCustomization {
    metafield(namespace: "payment-customization", key: "function-configuration") {
      value
    }
  }
}

**Comment by Rronz** [comment]
@nickwesselman that works. Would adding customer: Customer! in the schema.graphql be a bad idea?

**Comment by nickwesselman** [comment]
@Rronz Yes it would. 😁 Your function will definitely be executed without a buyer identity and/or customer, depending on the state of the buyer journey. Rust does not have null values so `None` cases need to be handled explicitly.
