### ISSUE TITLE
Provide documentation / function to create Decimals

### ISSUE THREAD

**Issue by theCapypara** [Shopify/shopify-function-rust#22]
Currently the crate has no documentation or function to create `Decimal`s, which are internally just `String`s. From what I understand, they are the same as the Admin API `Decimal`s (https://shopify.dev/docs/api/admin-graphql/2023-01/scalars/Decimal).

It would probably be useful and eliminate sources of errors, if the crate had a utility function to format Rusts built-in number types as Decimals and/or to implement a proper Decimal type or use a proper Decimal type of another crate.
At the very least, there should be some documentation in the crate on what values `Decimal`s should have (see link to Admin API).

**Comment by adampetro** [comment]
A decimal helper type was introduced in #34 and released in version `0.4.0`. Feel free to reopen if you have any issues with it
